/*
Created: 25/03/2019
Modified: 25/03/2019
Model: Microsoft SQL Server 2017
Database: MS SQL Server 2017
*/


-- Create schemas section -------------------------------------------------

CREATE SCHEMA [carga]
go

-- Create tables section -------------------------------------------------

-- Table MATERIAL

CREATE TABLE [MATERIAL]
(
 [ID_MATERIAL] Int IDENTITY NOT NULL,
 [ID_CONTENT] Int NULL,
 [TOTALELEMENTS] Int NULL,
 [TOTALPAGES] Int NULL,
 [LASTPAGE] Bit NULL,
 [NUMBERSELEMENTS] Int NULL,
 [FIRSTPAGE] Bit NULL,
 [SORT] Int NULL,
 [NUMBER] Int NULL,
 [SIZE] Int NULL
)
go

-- Add keys for table MATERIAL

ALTER TABLE [MATERIAL] ADD CONSTRAINT [ID_MATERIAL] PRIMARY KEY ([ID_MATERIAL])
go

-- Table CONTENT_MATERIAL

CREATE TABLE [CONTENT_MATERIAL]
(
 [ID_CONTENT] Int IDENTITY NOT NULL,
 [ID_MATERIAL] Int NULL,
 [ID_EMPRESA] Int NOT NULL,
 [ID_MSG] Int NOT NULL,
 [PROCESSO] Varchar(40) NULL,
 [DESC_PRODUTO] Varchar(max) NULL,
 [COD_ANV] Numeric(18,0) NULL,
 [SITUACAO] Varchar(4000) NULL
)
go

-- Add keys for table CONTENT_MATERIAL

ALTER TABLE [CONTENT_MATERIAL] ADD CONSTRAINT [Key2] PRIMARY KEY ([ID_CONTENT])
go

-- Table EMPRESA

CREATE TABLE [EMPRESA]
(
 [ID_EMPRESA] Int IDENTITY NOT NULL,
 [CNPJ] Varchar(20) NULL,
 [RAZAO_SOCIAL] Varchar(2000) NULL,
 [NUMEROAUTORIZACAO] Int NULL,
 [CNPJFORMATADO] Varchar(30) NULL,
 [AUTORIZACAO] Varchar(2000) NULL
)
go

-- Add keys for table EMPRESA

ALTER TABLE [EMPRESA] ADD CONSTRAINT [Key3] PRIMARY KEY ([ID_EMPRESA])
go

-- Table MENSAGEM

CREATE TABLE [MENSAGEM]
(
 [ID_MSG] Int IDENTITY NOT NULL,
 [SITUACAO] Varchar(2000) NULL,
 [RESOLUCAO] Varchar(2000) NULL,
 [MOTIVO] Varchar(2000) NULL,
 [NEGATIVO] Bit NULL
)
go

-- Add keys for table MENSAGEM

ALTER TABLE [MENSAGEM] ADD CONSTRAINT [Key4] PRIMARY KEY ([ID_MSG])
go

-- Create foreign keys (relationships) section ------------------------------------------------- 


ALTER TABLE [CONTENT_MATERIAL] ADD CONSTRAINT [FK_EMPRESA_CONTENT] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [EMPRESA] ([ID_EMPRESA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [CONTENT_MATERIAL] ADD CONSTRAINT [FK_ID_MATERIAL_CONTENT] FOREIGN KEY ([ID_MATERIAL]) REFERENCES [MATERIAL] ([ID_MATERIAL]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [CONTENT_MATERIAL] ADD CONSTRAINT [FK_CONTENT_MSG] FOREIGN KEY ([ID_MSG]) REFERENCES [MENSAGEM] ([ID_MSG]) ON UPDATE NO ACTION ON DELETE NO ACTION
go




