USE SUPORTE_II


DELETE carga.FABRICANTE_APRESENTACAO
 
DELETE carga.ACESSORIOS_APRESENTACAO

DELETE carga.ADMINISTRACAO_APRESENTACAO

DELETE carga.CONSERVACAO_APRESENTACAO

DELETE carga.DESTINACAO_APRESENTACAO

DELETE carga.DESTINACAO 
DBCC CHECKIDENT('carga.DESTINACAO',RESEED, 0) 


DELETE carga.FORMAS_APRESENTACAO

DELETE carga.FORMAS_FARMACEUTICAS
DBCC CHECKIDENT('carga.FORMAS_FARMACEUTICAS',RESEED, 0) 


DELETE carga.FABRICANTE_MEDICAMENTO
DBCC CHECKIDENT('carga.FABRICANTE_MEDICAMENTO',RESEED, 0) 

DELETE carga.EMBALAGEM_PRIMARIA
DBCC CHECKIDENT('carga.EMBALAGEM_PRIMARIA',RESEED, 0) 

DELETE carga.EMBALAGEM_SECUNDARIA 
DBCC CHECKIDENT('carga.EMBALAGEM_SECUNDARIA',RESEED, 0) 


DELETE carga.APRESENTACAO
DBCC CHECKIDENT('carga.APRESENTACAO',RESEED, 0) 


DELETE carga.CLASSE_MEDICAMENTO
 
DELETE carga.CLASSE_TERAPEUTICA
DBCC CHECKIDENT('carga.CLASSE_TERAPEUTICA',RESEED, 0) 

DELETE carga.MEDICAMENTO_CONTENT
DBCC CHECKIDENT('carga.MEDICAMENTO_CONTENT',RESEED, 0) 

DELETE carga.EMPRESA
DBCC CHECKIDENT('carga.EMPRESA',RESEED, 0) 

DELETE carga.PROCESSO
DBCC CHECKIDENT('carga.PROCESSO',RESEED, 0)




