

DELETE carga.ACESSORIOS_APRESENTACAO
DELETE carga.ADMINISTRACAO_APRESENTACAO
DELETE carga.APRESENTACAO_CONTENT
DELETE carga.CLASSE_MEDICAMENTO
DELETE carga.CONSERVACAO_APRESENTACAO
DELETE carga.DESTINACAO_APRESENTACAO
DELETE carga.ENVOLTORIO_APRESENTACAO
DELETE carga.FABRICANTE_APRESENTACAO
DELETE carga.FABRICANTE_CONTENT
DELETE carga.MARCA_APRESENTACAO
DELETE carga.ROTULO_MEDICAMENTO
DELETE carga.RESTRICAO_US0_APRESENTACAO
DELETE carga.RESTRICAO_PRESC_APRESENTACAO
DELETE carga.PRINCIPIO_ATIVO_APRESENTACAO
DELETE carga.FORMAS_APRESENTACAO

DELETE carga.ACESSORIOS
DBCC CHECKIDENT('carga.ACESSORIOS', RESEED, 0)

DELETE carga.ADMINISTRACAO
DBCC CHECKIDENT('carga.ADMINISTRACAO', RESEED, 0)

DELETE carga.APRESENTACAO
DBCC CHECKIDENT('carga.APRESENTACAO', RESEED, 0)

DELETE carga.APRESENTACAOMATERIAL
DBCC CHECKIDENT('carga.APRESENTACAOMATERIAL', RESEED, 0)

DELETE carga.CONTENT_MATERIAL
DBCC CHECKIDENT('carga.CONTENT_MATERIAL', RESEED, 0)

DELETE carga.CLASSE_RISCO
DBCC CHECKIDENT('carga.CLASSE_RISCO', RESEED, 0)

DELETE carga.CLASSE_TERAPEUTICA
DBCC CHECKIDENT('carga.CLASSE_TERAPEUTICA', RESEED, 0)

DELETE carga.CONSERVACAO
DBCC CHECKIDENT('carga.CONSERVACAO', RESEED, 0)

DELETE carga.DESTINACAO
DBCC CHECKIDENT('carga.DESTINACAO', RESEED, 0)

DELETE carga.EMBALAGEM_PRIMARIA
DBCC CHECKIDENT('carga.EMBALAGEM_PRIMARIA', RESEED, 0)

DELETE carga.EMBALAGEM_SECUNDARIA
DBCC CHECKIDENT('carga.EMBALAGEM_SECUNDARIA', RESEED, 0)

DELETE carga.MEDICAMENTO_CONTENT
DBCC CHECKIDENT('carga.MEDICAMENTO_CONTENT', RESEED, 0)

DELETE carga.EMPRESA
DBCC CHECKIDENT('carga.EMPRESA', RESEED, 0)

DELETE carga.ENVOLTORIOS
DBCC CHECKIDENT('carga.ENVOLTORIOS', RESEED, 0)

DELETE carga.FABRICANTE
DBCC CHECKIDENT('carga.FABRICANTE', RESEED, 0)

DELETE carga.FORMAS_FARMACEUTICAS
DBCC CHECKIDENT('carga.FORMAS_FARMACEUTICAS', RESEED, 0)

DELETE carga.MARCA
DBCC CHECKIDENT('carga.MARCA', RESEED, 0)

DELETE carga.MATERIAL
DBCC CHECKIDENT('carga.MATERIAL', RESEED, 0)

DELETE carga.MENSAGEM
DBCC CHECKIDENT('carga.MENSAGEM', RESEED, 0)

DELETE carga.PRINCIPIO_ATIVO
DBCC CHECKIDENT('carga.PRINCIPIO_ATIVO', RESEED, 0)

DELETE carga.PROCESSO
DBCC CHECKIDENT('carga.PROCESSO', RESEED, 0)

DELETE carga.RESTRICAO_PRESCRICAO
DBCC CHECKIDENT('carga.RESTRICAO_PRESCRICAO', RESEED, 0)

DELETE carga.RESTRICAO_USO
DBCC CHECKIDENT('carga.RESTRICAO_USO', RESEED, 0)

DELETE carga.ROTULO
DBCC CHECKIDENT('carga.ROTULO', RESEED, 0)
