
SELECT * FROM carga.ACESSORIOS_APRESENTACAO
SELECT * FROM carga.ADMINISTRACAO_APRESENTACAO
SELECT * FROM carga.APRESENTACAO_CONTENT
SELECT * FROM carga.CLASSE_MEDICAMENTO
SELECT * FROM carga.CONSERVACAO_APRESENTACAO
SELECT * FROM carga.DESTINACAO_APRESENTACAO
SELECT * FROM carga.ENVOLTORIO_APRESENTACAO
SELECT * FROM carga.FABRICANTE_APRESENTACAO
SELECT * FROM carga.FABRICANTE_CONTENT
SELECT * FROM carga.MARCA_APRESENTACAO
SELECT * FROM carga.ROTULO_MEDICAMENTO
SELECT * FROM carga.RESTRICAO_US0_APRESENTACAO
SELECT * FROM carga.RESTRICAO_PRESC_APRESENTACAO
SELECT * FROM carga.PRINCIPIO_ATIVO_APRESENTACAO
SELECT * FROM carga.FORMAS_APRESENTACAO

SELECT * FROM carga.ACESSORIOS
SELECT * FROM carga.ADMINISTRACAO
SELECT * FROM carga.APRESENTACAO
SELECT * FROM carga.APRESENTACAOMATERIAL
SELECT * FROM carga.CONTENT_MATERIAL
SELECT * FROM carga.CLASSE_RISCO
SELECT * FROM carga.CLASSE_TERAPEUTICA
SELECT * FROM carga.CONSERVACAO 
SELECT * FROM carga.DESTINACAO 
SELECT * FROM carga.EMBALAGEM_PRIMARIA
SELECT * FROM carga.EMBALAGEM_SECUNDARIA
SELECT * FROM carga.MEDICAMENTO_CONTENT
SELECT * FROM carga.EMPRESA
SELECT * FROM carga.ENVOLTORIOS
SELECT * FROM carga.FABRICANTE  --- ALTERAR PROCEDURE
SELECT * FROM carga.FORMAS_FARMACEUTICAS
SELECT * FROM carga.MATERIAL
SELECT * FROM carga.MENSAGEM
SELECT * FROM carga.PRINCIPIO_ATIVO 
SELECT * FROM carga.PROCESSO
SELECT * FROM carga.RESTRICAO_PRESCRICAO
SELECT * FROM carga.RESTRICAO_USO

SELECT * FROM carga.ROTULO
SELECT * FROM carga.MARCA








SELECT * FROM carga.MEDICAMENTO_CONTENT
SELECT * FROM carga.PROCESSO 
SELECT * FROM carga.CLASSE_TERAPEUTICA 
SELECT  * FROM carga.CLASSE_MEDICAMENTO
SELECT * FROM carga.APRESENTACAO 
SELECT * FROM carga.FABRICANTE_APRESENTACAO

SELECT * FROM carga.ADMINISTRACAO
SELECT * FROM carga.ADMINISTRACAO_APRESENTACAO

SELECT * FROM carga.CONSERVACAO_APRESENTACAO  
SELECT * FROM carga.CONSERVACAO

SELECT * FROM carga.PRINCIPIO_ATIVO_APRESENTACAO 
SELECT * FROM carga.PRINCIPIO_ATIVO     


