/*
Created: 25/03/2019
Modified: 02/04/2019
Model: Microsoft SQL Server 2017
Database: MS SQL Server 2017
*/


-- Create schemas section -------------------------------------------------

CREATE SCHEMA [carga]
go

-- Create tables section -------------------------------------------------

-- Table carga.MATERIAL

CREATE TABLE [carga].[MATERIAL]
(
 [ID_MATERIAL] Int IDENTITY NOT NULL,
 [TOTALELEMENTS] Int NULL,
 [TOTALPAGES] Int NULL,
 [LASTPAGE] Bit NULL,
 [NUMBERSELEMENTS] Int NULL,
 [FIRSTPAGE] Bit NULL,
 [SORT] Int NULL,
 [NUMBER] Int NULL,
 [SIZE] Int NULL
)
go

-- Add keys for table carga.MATERIAL

ALTER TABLE [carga].[MATERIAL] ADD CONSTRAINT [ID_MATERIAL] PRIMARY KEY ([ID_MATERIAL])
go

-- Table carga.MEDICAMENTO_CONTENT

CREATE TABLE [carga].[MEDICAMENTO_CONTENT]
(
 [MEDICAMENTO_ID] Int NOT NULL,
 [PROCESSO_ID] Int NOT NULL,
 [CLASSE_TERAPEUTICA_ID] Int NULL,
 [ROTULO_ID] Int NULL,
 [ID_EMPRESA] Int NULL,
 [CODIGO_PROD] Int NULL,
 [TIPO_PROD] Int NULL,
 [DATA_PROD] Date NULL,
 [NOME_COMERCIAL] Varchar(max) NULL,
 [COD_ANVISA_MED] Numeric(18,0) NULL,
 [DATA_VENCIMENTO] Date NULL,
 [MES_ANO_VENCIMENTO] Varchar(10) NULL,
 [COD_PARECER_PUBLICO] Varchar(50) NULL,
 [DATA_VENCIMENTO_REGISTRO] Date NULL,
 [PRINCIPIO_ATIVO] Varchar(200) NULL,
 [MEDICAMENTO_REFERENCIA] Varchar(200) NULL,
 [CATEGORIA_TERAPEUTICA] Varchar(200) NULL,
 [ATC] Varchar(100) NULL,
 [APRESENTACAO_ID] Int NULL,
 [COD_BULA_PACIENTES] Varchar(2000) NULL,
 [COD_BULA_PROFISSIONAL] Varchar(2000) NULL
)
go

-- Add keys for table carga.MEDICAMENTO_CONTENT

ALTER TABLE [carga].[MEDICAMENTO_CONTENT] ADD CONSTRAINT [MEDICAMENTO_ID] PRIMARY KEY ([MEDICAMENTO_ID])
go

-- Table carga.CONTENT_MATERIAL

CREATE TABLE [carga].[CONTENT_MATERIAL]
(
 [CONTENT_ID] Int IDENTITY NOT NULL,
 [MATERIAL_ID] Int NULL,
 [EMPRESA_ID] Int NOT NULL,
 [MSG_ID] Int NOT NULL,
 [VENCIMENTO_ID] Int NULL,
 [CLASSE_RISCO_ID] Int NULL,
 [PROCESSO] Varchar(40) NULL,
 [DESC_PRODUTO] Varchar(max) NULL,
 [COD_ANV] Numeric(18,0) NULL,
 [SITUACAO] Varchar(4000) NULL,
 [NOME_TECNICO] Varchar(4000) NULL,
 [CANCELADO] Bit NULL,
 [DATA_CANCELAMENTO] Date NULL,
 [PUBLICACAO] Date NULL,
 [APRESENTACAOMODELO] Bit NULL
)
go

-- Add keys for table carga.CONTENT_MATERIAL

ALTER TABLE [carga].[CONTENT_MATERIAL] ADD CONSTRAINT [CONTENT_ID] PRIMARY KEY ([CONTENT_ID])
go

-- Table carga.CLASSE_TERAPEUTICA

CREATE TABLE [carga].[CLASSE_TERAPEUTICA]
(
 [CLASSE_TERAPEUTICA_ID] Int NOT NULL,
 [CLASSE_TERAPEUTICA_DESC] Varchar(300) NULL
)
go

-- Add keys for table carga.CLASSE_TERAPEUTICA

ALTER TABLE [carga].[CLASSE_TERAPEUTICA] ADD CONSTRAINT [CLASSE_TERAPEUTICA_ID] PRIMARY KEY ([CLASSE_TERAPEUTICA_ID])
go

-- Table carga.EMPRESA

CREATE TABLE [carga].[EMPRESA]
(
 [ID_EMPRESA] Int IDENTITY NOT NULL,
 [CNPJ] Varchar(20) NULL,
 [RAZAO_SOCIAL] Varchar(2000) NULL,
 [NUMEROAUTORIZACAO] Int NULL,
 [CNPJFORMATADO] Varchar(30) NULL,
 [AUTORIZACAO] Varchar(2000) NULL
)
go

-- Add keys for table carga.EMPRESA

ALTER TABLE [carga].[EMPRESA] ADD CONSTRAINT [ID_EMPRESA] PRIMARY KEY ([ID_EMPRESA])
go

-- Table carga.PROCESSO

CREATE TABLE [carga].[PROCESSO]
(
 [PROCESSO_ID] Int NOT NULL,
 [NUMERO_PROCESSO] Int NULL,
 [SITUACAO] Int NULL,
 [PROCESSO_FORMARADO] Varchar(30) NULL
)
go

-- Add keys for table carga.PROCESSO

ALTER TABLE [carga].[PROCESSO] ADD CONSTRAINT [PROCESSO_ID] PRIMARY KEY ([PROCESSO_ID])
go

-- Table carga.MENSAGEM

CREATE TABLE [carga].[MENSAGEM]
(
 [ID_MSG] Int IDENTITY NOT NULL,
 [SITUACAO] Varchar(2000) NULL,
 [RESOLUCAO] Varchar(2000) NULL,
 [MOTIVO] Varchar(2000) NULL,
 [NEGATIVO] Bit NULL
)
go

-- Add keys for table carga.MENSAGEM

ALTER TABLE [carga].[MENSAGEM] ADD CONSTRAINT [ID_MSG] PRIMARY KEY ([ID_MSG])
go

-- Table carga.ROTULO

CREATE TABLE [carga].[ROTULO]
(
 [ROTULO_ID] Int NOT NULL,
 [ROTULO_DESC] Varchar(500) NULL
)
go

-- Add keys for table carga.ROTULO

ALTER TABLE [carga].[ROTULO] ADD CONSTRAINT [ROTULO_ID] PRIMARY KEY ([ROTULO_ID])
go

-- Table carga.APRESENTACAOMATERIAL

CREATE TABLE [carga].[APRESENTACAOMATERIAL]
(
 [APRESENTACAO_ID] Int IDENTITY NOT NULL,
 [MODELO] Varchar(max) NULL,
 [COMPONENTE] Varchar(max) NULL,
 [APRESENTACAO] Varchar(max) NULL
)
go

-- Add keys for table carga.APRESENTACAOMATERIAL

ALTER TABLE [carga].[APRESENTACAOMATERIAL] ADD CONSTRAINT [APRESENTACAO_ID] PRIMARY KEY ([APRESENTACAO_ID])
go

-- Table carga.APRESENTACAO

CREATE TABLE [carga].[APRESENTACAO]
(
 [APRESENTACAO_ID] Int NOT NULL,
 [MEDICAMENTO_ID] Int NULL,
 [EMBALAGEM_PRIMARIA_ID] Int NULL,
 [EMBALAGEM_SECUNDARIA_ID] Int NULL,
 [COD_APRESENTACAO] Int NULL,
 [APRESENTACAO] Varchar(500) NULL,
 [NUMERO_APRESENTACAO] Int NULL,
 [TOTALIDADE_APRESENTACAO] Int NULL,
 [DATA_PUBLICACAO] Date NULL,
 [VALIDADE_PROD_MESES] Int NULL,
 [TIPO_VALIDADE] Int NULL,
 [COD_ANV_APRESENTACAO] Numeric(18,0) NULL,
 [COMPLEMENTO_APRESENTACAO] Varchar(500) NULL,
 [ENVOLTORIOS_ID] Int NULL,
 [ACESSORIOS] Int NULL,
 [ACONDICIONADO] Varchar(500) NULL,
 [MARCA_ID] Int NULL,
 [VIAS_ADMINISTRACAO] Varchar(200) NULL,
 [IF_UNICO] Bit NULL,
 [RESTRICAO_HOSPITAIS] Bit NULL,
 [MEDICAMENTO_REFERENCIA] Bit NULL,
 [APRESENTACAO_FRACIONADA] Bit NULL,
 [DATA_VENCIMENTO_REGISTRO] Date NULL,
 [ATIVO] Bit NULL,
 [INATIVO] Bit NULL,
 [EM_ANALISE] Bit NULL
)
go

-- Add keys for table carga.APRESENTACAO

ALTER TABLE [carga].[APRESENTACAO] ADD CONSTRAINT [key] PRIMARY KEY ([APRESENTACAO_ID])
go

-- Table carga.FABRICANTE

CREATE TABLE [carga].[FABRICANTE]
(
 [FABRICANTE_ID] Int IDENTITY NOT NULL,
 [ATIVIDADE] Varchar(2000) NULL,
 [RAZAOSOCIAL] Varchar(2000) NULL,
 [PAIS] Varchar(300) NULL,
 [LOCAL] Varchar(300) NULL
)
go

-- Add keys for table carga.FABRICANTE

ALTER TABLE [carga].[FABRICANTE] ADD CONSTRAINT [FABRICANTE_ID] PRIMARY KEY ([FABRICANTE_ID])
go

-- Table carga.FORMAS_FARMACEUTICAS

CREATE TABLE [carga].[FORMAS_FARMACEUTICAS]
(
 [FORMAS_FARMACEUTICAS_ID] Int NOT NULL,
 [FORMAS_FARMACEUTICAS_DESC] Varchar(500) NULL
)
go

-- Add keys for table carga.FORMAS_FARMACEUTICAS

ALTER TABLE [carga].[FORMAS_FARMACEUTICAS] ADD CONSTRAINT [Key8] PRIMARY KEY ([FORMAS_FARMACEUTICAS_ID])
go

-- Table carga.CLASSE_RISCO

CREATE TABLE [carga].[CLASSE_RISCO]
(
 [CLASSE_RISCO_ID] Int IDENTITY NOT NULL,
 [SIGLA] Varchar(5) NULL,
 [DESCRICAO] Varchar(500) NULL
)
go

-- Add keys for table carga.CLASSE_RISCO

ALTER TABLE [carga].[CLASSE_RISCO] ADD CONSTRAINT [CLASSE_RISCO_ID] PRIMARY KEY ([CLASSE_RISCO_ID])
go

-- Table carga.FORMAS_APRESENTACAO

CREATE TABLE [carga].[FORMAS_APRESENTACAO]
(
 [APRESENTACAO_ID] Int NULL,
 [FORMAS_FARMACEUTICAS_ID] Int NULL
)
go

-- Table carga.VENCIMENTO

CREATE TABLE [carga].[VENCIMENTO]
(
 [VENCIMENTO_ID] Int IDENTITY NOT NULL,
 [DATA] Date NULL,
 [DESCRICAO] Varchar(2000) NULL
)
go

-- Add keys for table carga.VENCIMENTO

ALTER TABLE [carga].[VENCIMENTO] ADD CONSTRAINT [VENCIMENTO_ID] PRIMARY KEY ([VENCIMENTO_ID])
go

-- Table carga.PRINCIPIO_ATIVO

CREATE TABLE [carga].[PRINCIPIO_ATIVO]
(
 [PRINCIPIO_ATIVO_ID] Int NOT NULL,
 [PRINCIPIO_ATIVO_DESC] Varchar(500) NULL
)
go

-- Add keys for table carga.PRINCIPIO_ATIVO

ALTER TABLE [carga].[PRINCIPIO_ATIVO] ADD CONSTRAINT [PRINCIPIO_ATIVO_ID] PRIMARY KEY ([PRINCIPIO_ATIVO_ID])
go

-- Table carga.APRESENTACAO_CONTENT

CREATE TABLE [carga].[APRESENTACAO_CONTENT]
(
 [APRESENTACAO_ID] Int NULL,
 [CONTENT_ID] Int NULL
)
go

-- Table carga.PRINCIPIO_ATIVO_APRESENTACAO

CREATE TABLE [carga].[PRINCIPIO_ATIVO_APRESENTACAO]
(
 [PRINCIPIO_ATIVO_ID] Int NULL,
 [APRESENTACAO_ID] Int NULL
)
go

-- Table carga.FABRICANTE_CONTENT

CREATE TABLE [carga].[FABRICANTE_CONTENT]
(
 [CONTENT_ID] Int NULL,
 [FABRICANTE_ID] Int NULL
)
go

-- Table carga.ENVOLTORIOS

CREATE TABLE [carga].[ENVOLTORIOS]
(
 [ENVOLTORIOS_ID] Int NOT NULL,
 [ENVOLTORIOS_DESC] Varchar(500) NULL
)
go

-- Add keys for table carga.ENVOLTORIOS

ALTER TABLE [carga].[ENVOLTORIOS] ADD CONSTRAINT [ENVOLTORIOS_ID] PRIMARY KEY ([ENVOLTORIOS_ID])
go

-- Table carga.ENVOLTORIO_APRESENTACAO

CREATE TABLE [carga].[ENVOLTORIO_APRESENTACAO]
(
 [ENVOLTORIOS_ID] Int NULL,
 [APRESENTACAO_ID] Int NULL
)
go

-- Table carga.MARCA

CREATE TABLE [carga].[MARCA]
(
 [MARCA_ID] Int NOT NULL,
 [MARCA_DESC] Varchar(200) NULL
)
go

-- Add keys for table carga.MARCA

ALTER TABLE [carga].[MARCA] ADD CONSTRAINT [MARCA_ID] PRIMARY KEY ([MARCA_ID])
go

-- Table carga.MARCA_APRESENTACAO

CREATE TABLE [carga].[MARCA_APRESENTACAO]
(
 [MARCA_ID] Int NULL,
 [APRESENTACAO_ID] Int NULL
)
go

-- Table carga.FABRICANTES

CREATE TABLE [carga].[FABRICANTES]
(
 [FABRICANTES_ID] Int NOT NULL,
 [CNPJ] Varchar(20) NULL,
 [PAIS] Varchar(200) NULL,
 [UF] Varchar(200) NULL,
 [CIDADE] Varchar(500) NULL
)
go

-- Add keys for table carga.FABRICANTES

ALTER TABLE [carga].[FABRICANTES] ADD CONSTRAINT [FABRICANTES_ID] PRIMARY KEY ([FABRICANTES_ID])
go

-- Table carga.FABRICANTE_APRESENTACAO

CREATE TABLE [carga].[FABRICANTE_APRESENTACAO]
(
 [FABRICANTES_NACIONAIS_ID] Int NULL,
 [APRESENTACAO_ID] Int NULL,
 [TIPO_FAB] Char(1) NULL
)
go

-- Table carga.CONSERVACAO

CREATE TABLE [carga].[CONSERVACAO]
(
 [CONSERVACAO_ID] Int NOT NULL,
 [CONSERVACAO_DESC] Varchar(1000) NULL
)
go

-- Add keys for table carga.CONSERVACAO

ALTER TABLE [carga].[CONSERVACAO] ADD CONSTRAINT [CONSERVACAO_ID] PRIMARY KEY ([CONSERVACAO_ID])
go

-- Table carga.RESTRICAO_PRESCRICAO

CREATE TABLE [carga].[RESTRICAO_PRESCRICAO]
(
 [RESTRICAO_PRESCRICAO_ID] Int NOT NULL,
 [RESTRICAO_PRESCRICAO_DESC] Varchar(7000) NULL
)
go

-- Add keys for table carga.RESTRICAO_PRESCRICAO

ALTER TABLE [carga].[RESTRICAO_PRESCRICAO] ADD CONSTRAINT [RESTRICAO_PRESCRICAO_ID] PRIMARY KEY ([RESTRICAO_PRESCRICAO_ID])
go

-- Table carga.RESTRICAO_USO

CREATE TABLE [carga].[RESTRICAO_USO]
(
 [RESTRICAO_USO_ID] Int NOT NULL,
 [RESTRICAO_USO_DESC] Varchar(500) NULL
)
go

-- Add keys for table carga.RESTRICAO_USO

ALTER TABLE [carga].[RESTRICAO_USO] ADD CONSTRAINT [RESTRICAO_USO_ID] PRIMARY KEY ([RESTRICAO_USO_ID])
go

-- Table carga.DESTINACAO

CREATE TABLE [carga].[DESTINACAO]
(
 [DESTINACAO_ID] Int NOT NULL,
 [DESTINACAO_DESC] Varchar(300) NULL
)
go

-- Add keys for table carga.DESTINACAO

ALTER TABLE [carga].[DESTINACAO] ADD CONSTRAINT [DESTINACAO_ID] PRIMARY KEY ([DESTINACAO_ID])
go

-- Table carga.CONSERVACAO_APRESENTACAO

CREATE TABLE [carga].[CONSERVACAO_APRESENTACAO]
(
 [CONSERVACAO_ID] Int NULL,
 [APRESENTACAO_ID] Int NULL
)
go

-- Table carga.RESTRICAO_PRESC_APRESENTACAO

CREATE TABLE [carga].[RESTRICAO_PRESC_APRESENTACAO]
(
 [RESTRICAO_PRESCRICAO_ID] Int NULL,
 [APRESENTACAO_ID] Int NULL
)
go

-- Table carga.RESTRICAO_US0_APRESENTACAO

CREATE TABLE [carga].[RESTRICAO_US0_APRESENTACAO]
(
 [RESTRICAO_USO_ID] Int NULL,
 [APRESENTACAO_ID] Int NULL
)
go

-- Table carga.DESTINACAO_APRESENTACAO

CREATE TABLE [carga].[DESTINACAO_APRESENTACAO]
(
 [DESTINACAO_ID] Int NULL,
 [APRESENTACAO_ID] Int NULL
)
go

-- Table carga.EMBALAGEM_PRIMARIA

CREATE TABLE [carga].[EMBALAGEM_PRIMARIA]
(
 [EMBALAGEM_PRIMARIA_ID] Int NOT NULL,
 [EMBALAGEM_PRIMARIA_TIPO] Varchar(100) NULL,
 [EMBALAGEM_PRIMARIA_OBS] Varchar(200) NULL
)
go

-- Add keys for table carga.EMBALAGEM_PRIMARIA

ALTER TABLE [carga].[EMBALAGEM_PRIMARIA] ADD CONSTRAINT [EMBALAGEM_PRIMARIA_ID] PRIMARY KEY ([EMBALAGEM_PRIMARIA_ID])
go

-- Table carga.EMBALAGEM_SECUNDARIA

CREATE TABLE [carga].[EMBALAGEM_SECUNDARIA]
(
 [EMBALAGEM_SECUNDARIA_ID] Int NOT NULL,
 [EMBALAGEM_SECUNDARIA_TIPO] Varchar(200) NULL,
 [EMBALAGEM_SECUNDARIA_OBS] Varchar(200) NULL
)
go

-- Add keys for table carga.EMBALAGEM_SECUNDARIA

ALTER TABLE [carga].[EMBALAGEM_SECUNDARIA] ADD CONSTRAINT [EMBALAGEM_SECUNDARIA_ID] PRIMARY KEY ([EMBALAGEM_SECUNDARIA_ID])
go

-- Create foreign keys (relationships) section ------------------------------------------------- 


ALTER TABLE [carga].[CONTENT_MATERIAL] ADD CONSTRAINT [FK_EMPRESA_CONTENT] FOREIGN KEY ([EMPRESA_ID]) REFERENCES [carga].[EMPRESA] ([ID_EMPRESA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[CONTENT_MATERIAL] ADD CONSTRAINT [FK_ID_MATERIAL_CONTENT] FOREIGN KEY ([MATERIAL_ID]) REFERENCES [carga].[MATERIAL] ([ID_MATERIAL]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[CONTENT_MATERIAL] ADD CONSTRAINT [FK_CONTENT_MSG] FOREIGN KEY ([MSG_ID]) REFERENCES [carga].[MENSAGEM] ([ID_MSG]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[CONTENT_MATERIAL] ADD CONSTRAINT [FK_VENCIMENTO_CONTENT] FOREIGN KEY ([VENCIMENTO_ID]) REFERENCES [carga].[VENCIMENTO] ([VENCIMENTO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[CONTENT_MATERIAL] ADD CONSTRAINT [FK_CLASSE_RISCO_CONTENT] FOREIGN KEY ([CLASSE_RISCO_ID]) REFERENCES [carga].[CLASSE_RISCO] ([CLASSE_RISCO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[APRESENTACAO_CONTENT] ADD CONSTRAINT [FK_APRESENTACAO_CONTENT] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAOMATERIAL] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[APRESENTACAO_CONTENT] ADD CONSTRAINT [FK_CONTENT_APRESENTACAO] FOREIGN KEY ([CONTENT_ID]) REFERENCES [carga].[CONTENT_MATERIAL] ([CONTENT_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[FABRICANTE_CONTENT] ADD CONSTRAINT [FK_CONTENT_FABRICANTE] FOREIGN KEY ([CONTENT_ID]) REFERENCES [carga].[CONTENT_MATERIAL] ([CONTENT_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[FABRICANTE_CONTENT] ADD CONSTRAINT [FK_FABRICANTE_CONTENT] FOREIGN KEY ([FABRICANTE_ID]) REFERENCES [carga].[FABRICANTE] ([FABRICANTE_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[FORMAS_APRESENTACAO] ADD CONSTRAINT [FK_FORMAS_APRESENTACAO] FOREIGN KEY ([FORMAS_FARMACEUTICAS_ID]) REFERENCES [carga].[FORMAS_FARMACEUTICAS] ([FORMAS_FARMACEUTICAS_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[PRINCIPIO_ATIVO_APRESENTACAO] ADD CONSTRAINT [FK_PRINCIPIO_APRESENTACAO] FOREIGN KEY ([PRINCIPIO_ATIVO_ID]) REFERENCES [carga].[PRINCIPIO_ATIVO] ([PRINCIPIO_ATIVO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[ENVOLTORIO_APRESENTACAO] ADD CONSTRAINT [FK_ENV_APRES] FOREIGN KEY ([ENVOLTORIOS_ID]) REFERENCES [carga].[ENVOLTORIOS] ([ENVOLTORIOS_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[RESTRICAO_PRESC_APRESENTACAO] ADD CONSTRAINT [FK_REST_PRES_APRES] FOREIGN KEY ([RESTRICAO_PRESCRICAO_ID]) REFERENCES [carga].[RESTRICAO_PRESCRICAO] ([RESTRICAO_PRESCRICAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[DESTINACAO_APRESENTACAO] ADD CONSTRAINT [FK_APRES_DEST] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[DESTINACAO_APRESENTACAO] ADD CONSTRAINT [FK_DEST_APRES] FOREIGN KEY ([DESTINACAO_ID]) REFERENCES [carga].[DESTINACAO] ([DESTINACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[CONSERVACAO_APRESENTACAO] ADD CONSTRAINT [FK_CONSERVACAO_APRES] FOREIGN KEY ([CONSERVACAO_ID]) REFERENCES [carga].[CONSERVACAO] ([CONSERVACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[MARCA_APRESENTACAO] ADD CONSTRAINT [FK_MARCA_APRES] FOREIGN KEY ([MARCA_ID]) REFERENCES [carga].[MARCA] ([MARCA_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[CONSERVACAO_APRESENTACAO] ADD CONSTRAINT [FK_APRES_CONSERVACAO] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[RESTRICAO_PRESC_APRESENTACAO] ADD CONSTRAINT [FK_APRES_REST_PRES] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[RESTRICAO_US0_APRESENTACAO] ADD CONSTRAINT [FK_APRES_REST] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[RESTRICAO_US0_APRESENTACAO] ADD CONSTRAINT [FK_REST_APRES] FOREIGN KEY ([RESTRICAO_USO_ID]) REFERENCES [carga].[RESTRICAO_USO] ([RESTRICAO_USO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[FABRICANTE_APRESENTACAO] ADD CONSTRAINT [FK_APRES_FAB] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[APRESENTACAO] ADD CONSTRAINT [FK_EMB_PRI_APRESENTACAO] FOREIGN KEY ([EMBALAGEM_PRIMARIA_ID]) REFERENCES [carga].[EMBALAGEM_PRIMARIA] ([EMBALAGEM_PRIMARIA_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[APRESENTACAO] ADD CONSTRAINT [FK_EMB_SEC_APRESENTACAO] FOREIGN KEY ([EMBALAGEM_SECUNDARIA_ID]) REFERENCES [carga].[EMBALAGEM_SECUNDARIA] ([EMBALAGEM_SECUNDARIA_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[MEDICAMENTO_CONTENT] ADD CONSTRAINT [FK_CLASSE_MED] FOREIGN KEY ([CLASSE_TERAPEUTICA_ID]) REFERENCES [carga].[CLASSE_TERAPEUTICA] ([CLASSE_TERAPEUTICA_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[APRESENTACAO] ADD CONSTRAINT [FK_MEDICAMENTO_APRESENTACAO] FOREIGN KEY ([MEDICAMENTO_ID]) REFERENCES [carga].[MEDICAMENTO_CONTENT] ([MEDICAMENTO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[FABRICANTE_APRESENTACAO] ADD CONSTRAINT [FK_FAB_APRES] FOREIGN KEY ([FABRICANTES_NACIONAIS_ID]) REFERENCES [carga].[FABRICANTES] ([FABRICANTES_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[ENVOLTORIO_APRESENTACAO] ADD CONSTRAINT [FK_APRES_EV] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[FORMAS_APRESENTACAO] ADD CONSTRAINT [FK_APRESENTACAO_FORMAS] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[MARCA_APRESENTACAO] ADD CONSTRAINT [FK_APRES_MARCA] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[MEDICAMENTO_CONTENT] ADD CONSTRAINT [FK_ROTULO_MEDICAMENTO] FOREIGN KEY ([ROTULO_ID]) REFERENCES [carga].[ROTULO] ([ROTULO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[PRINCIPIO_ATIVO_APRESENTACAO] ADD CONSTRAINT [FK_APRESENTACAO_PRINCIPIO] FOREIGN KEY ([APRESENTACAO_ID]) REFERENCES [carga].[APRESENTACAO] ([APRESENTACAO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[MEDICAMENTO_CONTENT] ADD CONSTRAINT [FK_PROCESSO_MED] FOREIGN KEY ([PROCESSO_ID]) REFERENCES [carga].[PROCESSO] ([PROCESSO_ID]) ON UPDATE NO ACTION ON DELETE NO ACTION
go


ALTER TABLE [carga].[MEDICAMENTO_CONTENT] ADD CONSTRAINT [FK_EMPRESA_MED] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [carga].[EMPRESA] ([ID_EMPRESA]) ON UPDATE NO ACTION ON DELETE NO ACTION
go




